### ISSUE TITLE
CRITICAL: IPFS Companion exposes issue where Slate Gateway URLs are not resolving when the IPFS Companion Extension is enabled.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#342] opened 2020-09-29 18:51 UTC
###

This issue was reported by momack2. She reported that with [IPFS Companion Extension](https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch?hl=en) on Google Chrome, you could not view any of the image assets on https://slate.host. 

The original screenshot in the report included this:

![image](https://user-images.githubusercontent.com/310223/94602176-5fea7080-0249-11eb-870e-394b236de84e.png)

* I was able to deduce that the issue is not Metamask related.
* a1.jpg is a reference to an old default avatar we had that we have since removed.

### Reproduction
I was able to reproduce this bug by using Google Chrome, and the IPFS companion extension.

![](https://user-images.githubusercontent.com/310223/94602266-7d1f3f00-0249-11eb-8d06-6fa5b73776d3.png)

![](https://user-images.githubusercontent.com/310223/94602805-354ce780-024a-11eb-94f3-d37e85b1ed52.png)

Upon further investigation I was able to deduce that:

* Slate is still functional.
* All IPFS gateway URLs fail to resolve

You don't need to be running https://slate.host to reproduce this issue, you can just try to visit these URLS:

* https://slate.textile.io/ipfs/bafybeicbo4h434mbfz3ijfvrkydt7g5wvenzrjo4wh3bdjxzetrosbxiva
* https://slate.textile.io/ipfs/bafybeia25ygsr3zwmy2p3ol3piv7fkkev3rp3f62k53pxv2tmtzzm2mxnq
* https://slate.textile.io/ipfs/bafkreibp4qw5qq3bzgx5fbcz3bvznyc2xyjeevn3hhbjav35dl5fy7ew54

**Comment by sanderpick** [comment] 2020-09-29 19:18
Hey @jimmylee - My guess is that IPFS Companion naively parses outbound GET requests, snagging any that contain `/ipfs`.

**Comment by jimmylee** [comment] 2020-09-29 19:20
Thanks @sanderpick, pinging @lidel here in case that helps with the diagnosis

**Comment by olizilla** [comment] 2020-09-29 19:37
IPFS Companion will redirect urls that are valid IPFS addresses to the local IPFS deamon. That's the core feature. Are the images announced to the dht? Are their any discoverable provider records?

**Comment by lidel** [comment] 2020-09-29 19:37
I played with slate a bit and it works fine with Companion and my local go-ipfs 0.7.0, content is read from IPFS instead of `slate.textile.io/ipfs/..` and I get content integrity guarantees for free:

> ![2020-09-29--21-26-27](https://user-images.githubusercontent.com/157609/94606244-766ce800-029a-11eb-95cf-bc873b852000.png)

IIUC this is more or less expected behavior: you have IPFS Companion enabled, and by default it will load content from local IPFS node. **If the content is not there yet, it may take time for your node to find it and fetch it.**

So.. sounds like the problem you experience is slow content discovery when using a local IPFS node?
@jimmylee what type of local node you have? are you on slow network?
@sanderpick  is textile's gateway running go-ipfs 0.7.0? are you providing records to the network?

**Comment by jimmylee** [comment] 2020-09-29 19:40
(1) @momack2 was the first to report this issue, hopefully she can provide more details if her bandwidth provides

(2) I'm on WIFI with this speed:

<img width="464" alt="Screen Shot 2020-09-29 at 12 39 06 PM" src="https://user-images.githubusercontent.com/310223/94607470-d0e15680-0250-11eb-978a-7c01050b0a75.png">

Tagging @carsonfarmer so he might be able to provide details if bandwidth permits.

**Comment by jimmylee** [comment] 2020-09-29 19:41
Node Type:

<img width="1511" alt="Screen Shot 2020-09-29 at 12 40 45 PM" src="https://user-images.githubusercontent.com/310223/94607635-071ed600-0251-11eb-81ed-8a5e3cb02b11.png">

<img width="1489" alt="Screen Shot 2020-09-29 at 12 40 52 PM" src="https://user-images.githubusercontent.com/310223/94607658-0c7c2080-0251-11eb-9630-5d6f7e2c91c5.png">

I am using the out of the box config for IPFS companion. No custom settings @lidel

**Comment by lidel** [comment] 2020-09-29 19:47
Ok, after longer look, I believe this is not a problem with Companion, but Textile's nodes.

Not only my local node is unable to find CIDs you provided in the first comment:

```
$ ipfs refs -r bafkreibp4qw5qq3bzgx5fbcz3bvznyc2xyjeevn3hhbjav35dl5fy7ew54
```

But none of the public gateways, for example:

- https://ipfs.io/ipfs/bafkreibp4qw5qq3bzgx5fbcz3bvznyc2xyjeevn3hhbjav35dl5fy7ew54
- https://cloudflare-ipfs.com/ipfs/bafkreibp4qw5qq3bzgx5fbcz3bvznyc2xyjeevn3hhbjav35dl5fy7ew54

They hang forever.

**Comment by olizilla** [comment] 2020-09-29 19:50
@lidel an idle thought, companion could look up a dnsaddr record for the domain when it encounters IPFS urls. So `slate.host` could have a txt record like `/dnsaddr/slate.host/tcp/4001/ipfs/QmNodeyNodeNode` and while it redirects the requests to the local daemon, also try and connect to the suggested peer, to help with situations where it is difficult to publish all the provider records to the dht.

**Comment by jimmylee** [comment] 2020-09-29 19:52
@lidel @olizilla thank you for the next level debugging 🌸 I appreciate it!

**Comment by carsonfarmer** [comment] 2020-09-29 19:55
@lidel they appear to work perfectly fine for me? Even "fresh" slate cids.

**Comment by jimmylee** [comment] 2020-09-29 20:14
<img width="2266" alt="Screen Shot 2020-09-29 at 1 12 27 PM" src="https://user-images.githubusercontent.com/310223/94610772-a645cc80-0255-11eb-966b-cfba15c06beb.png">

A few other images started working 👀

**Comment by sanderpick** [comment] 2020-09-29 20:16
@lidel we're still on `ipfs/go-ipfs:v0.6.0`. The node is announcing records, but is currently NATed... which may account for the large discovery times. We're going to attach a public IP routed to that node's swarm port.

**Comment by lidel** [comment] 2020-09-29 20:21
@olizilla yes.. that would be _really_ elegant. Won't be easy as there is no Web API for dnsaddr lookup, nor we expose it in IPFS APIs. I created https://github.com/ipfs-shipyard/ipfs-companion/issues/925 to track this idea.

@carsonfarmer @jimmylee yeah, now I see them too. Looks like a really slow discovery for some reason. 

If I add unique CID to Slate, my local node is unable to find it unless I execute preload call to `https://node1.preload.ipfs.io/api/v0/refs?r=true&arg=<cid>`. I suspect preload nodes are peered with Textile, and that is how we are able to get them to the network. 

@sanderpick ah.. yeah, that would explain the above observation. Those nodes need to be publicly dialable for other nodes behind NAT  to be able to reach them.

**Comment by sanderpick** [comment] 2020-09-29 20:57
Sounds good! It's now publicly visible (`telnet 40.76.153.74 4001`) but not announcing there yet. We'll schedule some downtime tomorrow morning to get that going and update the node to `ipfs/go-ipfs:v0.7.0`.

**Comment by sanderpick** [comment] 2020-09-30 23:36
Reporting back here. That node is now running `ipfs/go-ipfs:v0.7.0` and is announcing a public IP:
```
Swarm announcing /ip4/40.76.153.74/tcp/4001
```

**Comment by lidel** [comment] 2020-10-01 14:45
I've added https://slate.textile.io/ipfs/bafkreid5w43amr736etsba7jkpyqlh4tb5powe3ftssd7f5ws5dkfeekqe but my local node is unable to find it via DHT (been looking for over 10 minutes+)

@sanderpick what is the PeerID of that machine? 
I want to confirm it is dialable from behind NAT (and that `ipfs dht findpeer` returns the address you mentioned).

**Comment by sanderpick** [comment] 2020-10-01 15:00
PeerID: `QmR69wtWUMm1TWnmuD4JqC1TWLZcc8iR2KrTenfZZbiztd`. 

From my local node,
```
⋊> ~ ipfs dht findpeer QmR69wtWUMm1TWnmuD4JqC1TWLZcc8iR2KrTenfZZbiztd
/ip4/40.76.153.74/tcp/4001
⋊> ~ ipfs swarm connect /ip4/40.76.153.74/tcp/4001/p2p/QmR69wtWUMm1TWnmuD4JqC1TWLZcc8iR2KrTenfZZbiztd
connect QmR69wtWUMm1TWnmuD4JqC1TWLZcc8iR2KrTenfZZbiztd success
```

But even after connecting, `ipfs get /ipfs/bafkreid5w43amr736etsba7jkpyqlh4tb5powe3ftssd7f5ws5dkfeekqe` hangs and hangs. More investigation needed.

**Comment by jimmylee** [comment] 2020-10-28 23:11
I need to double check if this is still a problem, I'll verify and ping the necessary parties again.

**Comment by lidel** [comment] 2020-11-12 13:36
@jimmylee  For what its worth I still experience the problem with content discovery of newly added content.

For example, when redirect in IPFS Companion is enabled, my local IPFS node is unable to find content from:
- https://slate.host/guji/%E5%8C%97%E4%BA%AC%E7%9A%87%E5%9F%8E%E5%BB%BA%E7%AD%91%E8%A3%85%E9%A5%B0
- https://slate.host/gndclouds/urban-gardens

What is concerning, is that it fails to find the content even if I manually connect to peer provided by @sanderpick:

```console
$ ipfs swarm connect /p2p/QmR69wtWUMm1TWnmuD4JqC1TWLZcc8iR2KrTenfZZbiztd
connect QmR69wtWUMm1TWnmuD4JqC1TWLZcc8iR2KrTenfZZbiztd success
```

A quick fix is to disable IPFS integration for `slate.host` website:
> ![2020-11-12--14-25-57](https://user-images.githubusercontent.com/157609/98945587-008fa980-24f3-11eb-8d68-0ca804b2c76b.png)


..but we really need to figure out the content discovery problem. 
Without this working, it had sell is just a centralized website.

Note that loading content from local IPFS node works fine on other websites that use content-addressed assets, such as  [Audius](https://audius.co/trending).  @jessicaschilling did [case study](https://docs.ipfs.io/concepts/case-study-audius/#overview) on Audius and can put you in touch with them if you'd like to compare notes on backend setup related to the way content is provided to the IPFS network.

**Comment by sanderpick** [comment] 2020-11-13 06:56
Hey @lidel @jimmylee sorry to have dropped the ball here. I just popped open this nodes logs and saw a number of these errors shown in [this issue](https://github.com/ipfs/go-ipfs/issues/7573):
```
2020-11-04T23:58:33.322Z	ERROR	dht	ignoring incoming dht message while not in server mode
```
However, the config is definitely not setup to be running in client mode. Maybe related to high CPU as mentioned in the issue above.

In any case, I also noticed that `"DisableNatPortMap"` was set to true. Out of curiosity, I flipped that to false. After restarting the node, I can `ipfs get` Slate Cids and browse the site IPFS Companion on. This node runs on a Kubernetes pod, so maybe something special is going on with the networking which requires the NAT port map. Another possibility is the node just needed a restart to reduce CPU... in which case this probably isn't a permanent fix.

**Comment by lidel** [comment] 2020-11-13 13:52
I get mixed results. Can confirm the content routing issue seems to be gone for links I posted (content was found fast and loads fine from my local node), however other ones (eg. https://slate.host/bitgraves/september) still struggle to find the content (`ipfs dht findprovs bafybeiensbi2qyx2fpyjhl32deplv264ewf2ceo5duypfmx6ykraf7nc3u` returns nothing).

Gut feeling: perhaps it only works when you are directly connected to the node in the pod?
If your local node was connected to the node in the pod, then you were able to cache the content form my links and then your local node started providing it to the network. This would explain why common links posted here work for me (pod+your laptop), but not the other stuff (only pod).





@sanderpick some ideas to try:

- See if `Reprovider.Interval` and `Reprovider.Strategy` are set to `all` and `12h` or something else
- If you are running behind NAT 
  - Try.. not doing that on the server, if possible  :-) 
    (not familiar with Kubernetes enough to tell if its feasible).

  - If you need to run behind NAT, 
    - Set [Routing.Type](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#routing) to `dhtclient`  to avoid `ignoring incoming dht message while not in server mode` in logs (sounds that Kubernetes NAT causes your node to switch into client mode anyway).
    - Try to [manually forward swarm ports](https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/), then  try [adding public IP+port to  `Addresses.Announce` list](https://discuss.ipfs.io/t/how-to-add-external-ip-to-ipfs-swarm-announcing-list/4647/3?u=lidel) to ensure publicly dialable address is published to DHT. This should help if your network topology is too complex for go-ipfs to infer its own publicly diallable address for some reason. 
- Did you apply `server` profile? 
  - https://docs.ipfs.io/reference/cli/#ipfs-config-profile-apply
  - https://github.com/ipfs/go-ipfs-config/blob/v0.10.0/profile.go#L52
    - iiuc it disables use of local addresses from being published to DHT, so client won't waste time trying  them
    - note that it overwrites existing config, so after applying the profile you need to set keys like `DisableNatPortMap` back if needed.
- Mind sharing full config? Perhaps something sticks out.

**Comment by sanderpick** [comment] 2020-11-13 15:47
> Gut feeling: perhaps it only works when you are directly connected to the node in the pod?

After a restart (low CPU), I was able to browse slate pages with fresh local node (no direct connection and no caching).

>     * See if `Reprovider.Interval` and `Reprovider.Strategy` are set to `all` and `12h` or something else

Yep, not changed from the default.

>     * If you are running behind NAT

No.
    
>       * If you need to run behind NAT,      
>         * Set [Routing.Type](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#routing) to `dhtclient`  to avoid `ignoring incoming dht message while not in server mode` in logs (sounds that Kubernetes NAT causes your node to switch into client mode anyway).

It appears that when the node goes under very high load (providing a huge amount of Cids), the connectivity suffers, and we see these `ignoring incoming dht message while not in server mode` errors. I'll compare results with a staging setup that has many fewer Cids.

>         * Try to [manually forward swarm ports](https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/), then  try [adding public IP+port to  `Addresses.Announce` list](https://discuss.ipfs.io/t/how-to-add-external-ip-to-ipfs-swarm-announcing-list/4647/3?u=lidel) to ensure publicly dialable address is published to DHT. This should help if your network topology is too complex for go-ipfs to infer its own publicly diallable address for some reason.

The public IP is included in `Addresses.Announce` as mentioned above.

>     * Did you apply `server` profile?

Partially. We can't use the address filters with Kubernetes. I can manually pluck the filters that will work, but I doubt that will solve the connectivity issue. `DisableNatPortMap` has previously been set to true, but as mentioned above I flipped it... though again I doubt this is related.

>     * Mind sharing full config? Perhaps something sticks out.

Sure, https://gist.github.com/sanderpick/7bd7eb045b31f17e14a80a408e4a1b10

**Comment by sanderpick** [comment] 2020-11-13 16:04
Idea from @jsign: Since this machine is only pinning buckets, would it be possible to _only_ provide recursively pinned Cids? That may reduce the load, and since a connection should then exist (at least intermittently), the other Cids will be indirectly discoverable.

In any case, I think we need some config tweaking to handle huge amounts of Cids. Any recommendations @lidel, @aschmahmann, @hsanjuan?

**Comment by jsign** [comment] 2020-12-15 13:35
Here are some experiments with the theory DHT reproviding being the cause of the issue.

*Use `pinned` reproviding strategy*:
![image](https://user-images.githubusercontent.com/6136245/102220710-f3822380-3ebf-11eb-8045-07770fb8bdce.png)
35hs approx to reach CPU limit.

*Use `roots` reproviding stragegy*:
![image](https://user-images.githubusercontent.com/6136245/102220847-21676800-3ec0-11eb-800a-11fc00c1abf6.png)
Some days to ~reach CPU limit.

So it seems that using `roots` alleviates the issue, but we still hit the limit.

While still running with `roots` I took a CPU pprof profile with the hot-path being:
![image](https://user-images.githubusercontent.com/6136245/102221596-14974400-3ec1-11eb-9d0a-9e6559e98435.png)
So it looks like most of CPU usage is related to querying peers in the DHT, so might also confirm is related to reproviding?

Some extra facts about this IPFS node below.

Stats:
```
NumObjects: 6163728
RepoSize:   1059479615925
StorageMax: 1000000000000
RepoPath:   /data/ipfs
Version:    fs-repo@10
```

The number of pins `--type=recursive` is: `122138`.
As shown in the CPU usage history, the node has a limit of vCPU (are these enough resources for this IPFS node size?).

**Comment by jsign** [comment] 2020-12-15 15:00
Peter recommended trying out a quite reasonable config change: disable QUIC.
We did, now we'll wait some hours and I'll report back here how this worked out.

**Comment by momack2** [comment] 2020-12-17 22:21
@aschmahmann and @jacobheun as FYI for the roots pinning profiles (these are gold @jsign!)

**Comment by aschmahmann** [comment] 2020-12-18 00:23
@momack2 we're in touch. I'm pretty sure those profiles have very little to do with providing since we are "finding providers" in that profile.

My guess is that this has to do with Textile having many IPNS over PubSub channels and periodically querying the DHT to find if anyone new has joined the channel. I suspect Textile is pushing this feature harder than most and with hundreds of topics per node is doing a lot of crawling. They're running some tests now where periodically searching for new PubSub peers is just disabled to see if that's really the issue. Once we've confirmed then we can discuss what the options are.

Note: I don't currently have a good guess as to why switching from providing pins to roots would be any less work for this machine since I don't think they're likely to be able to reprovide even 100k pin roots within the default 12 hr period.

**Comment by kuzdogan** [comment] 2022-01-28 14:21
> Hey @lidel @jimmylee sorry to have dropped the ball here. I just popped open this nodes logs and saw a number of these errors shown in [this issue](https://github.com/ipfs/go-ipfs/issues/7573):
> 
> ```
> 2020-11-04T23:58:33.322Z	ERROR	dht	ignoring incoming dht message while not in server mode
> ```
> 
> However, the config is definitely not setup to be running in client mode. Maybe related to high CPU as mentioned in the issue above.
> 
> In any case, I also noticed that `"DisableNatPortMap"` was set to true. Out of curiosity, I flipped that to false. After restarting the node, I can `ipfs get` Slate Cids and browse the site IPFS Companion on. This node runs on a Kubernetes pod, so maybe something special is going on with the networking which requires the NAT port map. Another possibility is the node just needed a restart to reduce CPU... in which case this probably isn't a permanent fix.

We are experiencing massive resource consumption on our nodes. It seemed to increase when we start getting the error above. Tried running on a server profile with `ipfs init --profile server` but didn't help. Also using `pinned` strategy. 

Anyone found a solution to this?

**Closed** 2022-03-13 20:10 UTC
Labels: Bug
