### ISSUE TITLE
HEIC image uploads sometimes result in image distortion after upload

### ISSUE THREAD

**Issue by harisbutt** [filecoin-project/slate#200] opened 2020-09-02 17:26 UTC
HEIC formatted images and up getting distorted after uploading to Slate. This happens sometimes (has only happened for me uploading multiple images at once), but shouldn't happen at all. Gotta say the distortion is actually kinda cool though...

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13544493/92016115-b6c26000-ed06-11ea-8f58-d4b2e7d75516.png">

Link to example here: https://bafybeiajck4jyxfjwxkyqorwzhnyxqsmy2b346ehgp7irbqwco2n427cia.ipfs.slate.textile.io/

**Comment by cwaring** [comment] 2020-12-02 17:28
Has anybody done any initial investigations to see if this is related to missing metadata or the way HEIC files are stored on textile/IPFS?

**Comment by jimmylee** [comment] 2020-12-03 02:15
I think its because of the way we do HEIC conversions on the client

https://github.com/filecoin-project/slate/blob/main/common/file-utilities.js#L45

But we don't have any tests for this. But any issues the https://github.com/alexcorvi/heic2any/issues team is experiencing we will most likely get them.

I'd like to move to a processing micro-service, preferably written in C++ or Go and do this on the server.

**Comment by cwaring** [comment] 2020-12-03 14:47
OK great to know. I'll see if I can patch the frontend for now and then we can plan out the server processing approach, I imagine this would be an aspect of the formats proxy/service.

**Comment by cwaring** [comment] 2020-12-03 16:42
@harisbutt do you have the original file that caused this issue? I've just tested with 6 different samples and am unable to reproduce this bug on prod or dev. Perhaps you could try again? There is a possibility that a library patch has fixed this recently.

![2020-12-03 at 16 41 36](https://user-images.githubusercontent.com/106938/101059738-8351d480-3586-11eb-8de8-1483a0bf659d.png)

**Comment by cwaring** [comment] 2021-01-18 16:56
Unable to recreate, closing for now.

**Closed by cwaring** 2021-01-18 16:56 UTC
Labels: Bug
